### ISSUE TITLE
Better separation of packages 

### ISSUE THREAD

**Issue by Dronakurl** [Dronakurl/storytime#6]
# Tasks
- [ ] Separation of packages and subpackages, so that the Story class can more easily be used in other projects
- [x] Write, backup the markdown file of generated story
- [x] Remove json functionality, as it is not needed
